In [1]:
# import custom functions
from get_candidates import get_candidates
from get_row_col import get_row_col
from convert_to_binary import convert_to_binary
from naked_for_how_long import naked_for_how_long

# other functions we need
from ast import literal_eval

import pandas as pd
import numpy as np

In [24]:
# import SQL dependencies
import sqlite3

# connect to .db
con = sqlite3.connect("../data-collection/nyt-sudoku.db")
cur = con.cursor()

doks_perf = pd.read_sql("SELECT * from doks_performance;",
           con)

doks_easy = pd.read_sql("SELECT * from doks_easy;",
           con)

doks_med = pd.read_sql("SELECT * from doks_medium;",
           con)

doks_hard = pd.read_sql("SELECT * from doks_hard;",
           con)

In [15]:
add_pct = lambda t: str(int(t)) + '%'
vfunc = np.vectorize(add_pct)

In [33]:
doks_easy['puzzle'] = doks_easy['puzzle'].apply(literal_eval)
doks_easy = doks_easy['puzzle'][:500]

In [44]:
easy_prefilled_grids=pd.DataFrame(doks_easy.tolist())

In [48]:
easy_prefilled_grids

0   1   2   3   4   5   6   7   8   9   ...  71  72  73  74  75  76  77  \
0     7   5   2   0   4   8   0   0   0   6  ...   6   0   6   7   0   5   0   
1     1   5   0   3   0   4   0   8   6   6  ...   0   0   7   2   1   0   9   
2     1   0   5   0   0   7   0   0   6   0  ...   8   4   2   0   5   7   0   
3     0   4   3   5   2   0   1   7   0   1  ...   1   7   6   1   4   0   0   
4     5   0   0   0   8   0   1   0   6   0  ...   0   1   2   5   9   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
495   1   5   6   0   0   8   0   2   0   0  ...   5   5   0   3   0   0   0   
496   0   6   0   2   0   0   1   0   4   3  ...   9   2   3   0   4   6   0   
497   1   0   0   4   0   0   5   2   7   7  ...   3   0   5   3   0   0   8   
498   3   0   9   6   0   0   8   1   0   0  ...   0   1   0   0   8   7   2   
499   0   0   3   0   4   0   6   0   5   0  ...   0   0   2   0   0   0   8   

     78  79  80  
0     3   9   0  
1     0   0   0  
2     0   0   0  
3     0   0   0  
4     0   0   0  
..   ..  ..  ..  
495   7   0   2  
496   0   0   7  
497   0   0   1  
498   9   0   0  
499   0   1   3  

[500 rows x 81 columns]

In [57]:
easy_prefilled_grids.to_csv('easy_prefilled_grids.csv', index=False)

In [56]:
(easy_prefilled_grids == 0).sum(axis=1)

0      43
1      43
2      43
3      43
4      43
       ..
495    43
496    43
497    43
498    43
499    43
Length: 500, dtype: int64

In [18]:
doks_easy = doks_easy.apply(convert_to_binary)

In [20]:
np.around(doks_easy.sum().reshape((9,9)) * 100 / len(doks_easy), decimals=0).flatten()

array([60., 58., 57., 57., 52., 51., 53., 48., 48., 55., 48., 53., 50.,
       49., 51., 51., 48., 50., 55., 42., 45., 49., 50., 50., 47., 50.,
       44., 48., 50., 46., 46., 55., 45., 50., 49., 44., 47., 48., 49.,
       48., 53., 43., 47., 45., 45., 45., 46., 44., 44., 42., 42., 45.,
       44., 41., 49., 49., 46., 44., 49., 46., 40., 44., 48., 46., 46.,
       51., 43., 39., 45., 43., 38., 41., 39., 41., 40., 41., 38., 43.,
       46., 41., 41.])

In [25]:
doks_med['puzzle'] = doks_med['puzzle'].apply(literal_eval)
doks_med = doks_med['puzzle'][:500]

In [27]:
doks_med = doks_med.apply(convert_to_binary)

In [28]:
(doks_med.sum().reshape((9,9)) * 100 / len(doks_med)).flatten().round()

array([27., 33., 26., 29., 28., 29., 30., 32., 33., 31., 28., 30., 28.,
       34., 32., 30., 30., 30., 30., 30., 27., 33., 31., 29., 34., 34.,
       32., 29., 29., 33., 30., 32., 30., 33., 33., 30., 31., 32., 35.,
       27., 33., 35., 29., 27., 27., 34., 30., 30., 28., 31., 28., 31.,
       27., 24., 27., 35., 34., 28., 29., 29., 27., 31., 29., 28., 24.,
       29., 33., 27., 27., 32., 27., 28., 27., 26., 27., 29., 30., 28.,
       26., 25., 28.])

In [29]:
doks_hard['puzzle'] = doks_hard['puzzle'].apply(literal_eval)
doks_hard = doks_hard['puzzle'][:500]

In [30]:
doks_hard = doks_hard.apply(convert_to_binary)

In [31]:
(doks_hard.sum().reshape((9,9)) * 100 / len(doks_hard)).flatten().round()

array([30., 27., 29., 29., 32., 28., 32., 26., 29., 31., 29., 32., 28.,
       29., 28., 31., 32., 33., 29., 31., 27., 34., 26., 31., 29., 34.,
       30., 31., 35., 32., 26., 29., 30., 35., 29., 31., 34., 29., 30.,
       32., 35., 27., 30., 32., 30., 27., 33., 30., 28., 29., 28., 27.,
       28., 28., 30., 27., 33., 32., 28., 26., 31., 28., 26., 24., 29.,
       29., 29., 31., 34., 28., 28., 28., 27., 29., 24., 26., 25., 29.,
       26., 25., 24.])